mode_info:
  name: "Mode 0"
  display_name: "Mode 0"
  description: "Mode similar to Jaco's control mode"
  default_image: "Mode_0.png"

button_mappings:
  B1:
    axes:
      - control_name: "complex_Y"
        joystick_axis: "ax1"
        direction: 1
        scale: 3.0
        image: "cartesian_Y.png"  
      - control_name: "complex_X"
        joystick_axis: "ax2"
        direction: 1
        scale: 3.0
        image: "cartesian_X.png"
    button:
      - long_click: "A1"
      - short_click: "B2"
    
      
  B2:
    axes:
      - control_name: "joint_6"
        joystick_axis: "ax1"
        direction: 1
        scale: 0.75
        image: "joint_6.png" 
      - control_name: "cartesian_Z"
        joystick_axis: "ax2"
        direction: 1
        scale: 3.0
        image: "cartesian_Z.png"
    button:
      - long_click: "DRINK"
      - short_click: "B3"
  
  DRINK:
    axes:
      - control_name: "drink"
        joystick_axis: "ax1"
        direction: 1
        scale: 0.75
        image: "joint_6.png" 
      - control_name: "cartesian_Z"
        joystick_axis: "ax2"
        direction: 1
        scale: 3.0
        image: "cartesian_Z.png" 
    button:
      - long_click: ""
      - short_click: "B2"

  B3:
    axes:
      - control_name: "rotation_Z"
        joystick_axis: "ax1"
        direction: 1
        scale: 0.75
        image: "rotation_Z.png"  
      - control_name: "rotation_Y"
        joystick_axis: "ax2"
        direction: 1
        scale: 0.75
        image: "rotation_Y.png" 
    button:
      - long_click: ""
      - short_click: "B4"

  B4:
    axes:
      - control_name: "gripper"
        joystick_axis: "ax1"
        direction: 1
        scale: 1.0
        image: "gripper.png"  
      - control_name: ""
        joystick_axis: ""
        direction: 0
        scale: 0.0
        image: ""
    button:
      - long_click: "A2"
      - short_click: "B1"

  A1:
    axes:
      - control_name: ""
        joystick_axis: ""
        direction: 0
        scale: 0.0
        image: ""
      - control_name: "change_speed"
        joystick_axis: "ax2"
        direction: 1
        scale: 1.0
        image: ""
    button:
      - long_click: ""
      - short_click: "B1"

  A2:
    axes:
      - control_name: ""
        joystick_axis: ""
        direction: 0
        scale: 0.0
        image: ""
      - control_name: "trajectory_control"
        joystick_axis: "ax2"
        direction: 1
        scale: 2.0
        image: ""
    button:
      - long_click: ""
      - short_click: "B4"
