qp_solving:
  ros__parameters:

    joint_number  : 6

    ### --- QP WEIGHTS --- ###
    #  Minimize cartesian velocity difference : dx - dx_des
    alpha_weight  : [4., 4., 4., 1., 1., 1., 1.]
    alpha_multiplier : 10
    #  Minimize joints velocities coefs : dq
    beta_weight   : [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    beta_multiplier : 1
    #  Minimize cartesian pose difference : x-x_des
    gamma_weight  : [1000.0, 1000.0, 1000.0, 250.0, 250.0, 250.0, 250.0]
    gamma_multiplier : 1

    ### --- JOINT LIMITS --- ###
    j1:
      limits  : 1 #int type, 0 if joint is multiturn or 1 otherwise
      min     : -3.14
      max     : 3.14
    j2:
      limits  : 1
      min     : -1.8
      max     : 1.8
    j3:
      limits  : 1
      min     : -4.71
      max     : 1.8
    j4:
      limits  : 1
      min     : -3.14
      max     : 3.14
    j5:
      limits  : 1
      min     : -3.14
      max     : 3.14
    j6:
      limits  : 1
      min     : -3.14
      max     : 3.14

    ### --- NAME OF SDRF GROUP --- ###
    model_group_name            : "arm"
    end_effector_name           : "tool0"

    joint_max_vel               : 0.5 


