controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    explorer_custom_controller:
      type: explorer_command_controllers/CustomController

explorer_custom_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - right_finger_joint
    settings:
      joint_1: { 
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        enable_limits: false,
        cmd_min: -0.2,
        cmd_max:  0.2,
        step_max: 0.0005,
        cmd_init_from_state: true,
        ref_mult: 0.01,
      }
      joint_2: {
        mode: "effort",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        enable_limits: false,
        cmd_min: -1.57,
        cmd_max: -0.78,
        step_max: 0.0005,
        cmd_init_from_state: true,
        ref_mult: 0.01,
      }
      joint_3: {
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        enable_limits: false,
        cmd_min: -0.78,
        cmd_max:  0.78,
        step_max: 0.0005,
        cmd_init_from_state: true,
        ref_mult: 0.01,
      }
      joint_4: {
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        enable_limits: false,
        cmd_min: -1.0,
        cmd_max:  1.0,
        step_max: 0.2,
        cmd_init_value: 0.0,
        cmd_init_from_state: false,
        ref_mult: 50.0,
      }
      joint_5: {
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        enable_limits: false,
        cmd_min: -1.0,
        cmd_max:  1.0,
        step_max: 0.2,
        cmd_init_value: 0.0,
        cmd_init_from_state: false,
        ref_mult: 50.0,
      }
      joint_6: {
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        enable_limits: false,
        cmd_min: -1.0,
        cmd_max:  1.0,
        step_max: 0.2,
        cmd_init_value: 0.0,
        cmd_init_from_state: false,
        ref_mult: 50.0,
      }
      right_finger_joint: {
        mode: "position",
        command_interface_names: ["position"],
        state_interface_names: ["position"],
        enable_limits: false,
        cmd_min:  0.15,
        cmd_max:  0.65,
        step_max: 0.001,
        cmd_init_from_state: false,
        cmd_init_value: 0.5,
        ref_mult: 0.01,
      }
