########################################
# Request
########################################
string cmd
uint8  wait_for_ms
---
########################################
# Response
########################################
string ret
