########################################
# Request
########################################
string joint_name
string mode
---
########################################
# Response
########################################
bool ret
