name: Build docker images (CI / dev / prod)
on:
    push:
      tags:
          - '**'
    # Manual trigger
    workflow_dispatch:
      inputs:
        target:
          type: choice
          default: all
          options: [all, CI, builder, dev-prod]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-CI-docker-image:
    ## Build CI image only on manual trigger (from any branch)
    if: ${{ github.event_name == 'workflow_dispatch' || inputs.target == 'all' || inputs.target == 'CI' }}
    uses: ./.github/workflows/workflow-docker-image.yml
    with:
      image_name: builder
      target: explorer_builder
    secrets: inherit

  build-and-push-dev-docker-image:
    if: ${{ github.event_name == 'push' || inputs.target == 'all' || inputs.target == 'dev' }}
    uses: ./.github/workflows/workflow-docker-image.yml
    with:
      image_name: dev
      target: explorer_dev
    secrets: inherit

  build-and-push-prod-docker-image:
    if: ${{ github.event_name == 'push' || inputs.target == 'all' || inputs.target == 'prod' }}
    uses: ./.github/workflows/workflow-docker-image.yml
    with:
      image_name: prod
      target: explorer_prod
    secrets: inherit